### ISSUE TITLE
Automate the sync of ciDict.json into all implementations

### ISSUE THREAD

**Issue by aurelien-reeves** [cucumber/create-meta#14]
Refs. https://github.com/cucumber/create-meta/pull/13

After cleaning-up the repository after the move from the monorepo (#6 ), we kept a single `ciDict.json` in the root folder, and referred to it using a relative path for the ruby and the java implementation.

But once released, `ciDict.json` was actually mising from the ruby gem and the java artifact.

A quick fix has been released as part of 6.0.4. But at the moment `ciDict.json` has just been manually copied from the root folder into java and ruby modules. A way to automatically sync the file would be welcome.

- [x] Java
- [x] JavaScript
- [ ] Ruby

**Comment by mpkorstanje** [comment]
Rather then copying the file you can have maven copy it when building. 

https://maven.apache.org/plugins/maven-resources-plugin/examples/copy-resources.html

**Comment by aurelien-reeves** [comment]
> Rather then copying the file you can have maven copy it when building java.
> 
> https://maven.apache.org/plugins/maven-resources-plugin/examples/copy-resources.html
> 

Great, thanks!
Now, we have to find something like that with ruby

> Don't merely copy the docs tough, I think there are a few gotchas in there.

What do you mean?

**Comment by aslakhellesoy** [comment]
@aurelien-reeves I'll start a PR for this, starting with a fix for Java...

**Comment by aurelien-reeves** [comment]
@aslakhellesoy thanks

Actually I have started to work on that. This is available here: https://github.com/cucumber/create-meta/tree/java/copy-cidict-json

I don't know if it is ok. It seems to work, but if we change ciDict.json and do `mvn install`, it seems to properly copy the new ciDict.json, but the tests are still failing. We have to execute ` mvn install` or ` mvn test` a second time for the tests to pass

**Comment by mpkorstanje** [comment]
If the tests need to be run twice it might be that you got the wrong phase. But the tests in CI pass.

**Comment by aurelien-reeves** [comment]
@mpkorstanje do you have some documentation regarding the phases?
The CI is passing because at the moment, the copied ciDict.json is still part of the repo. Not sure it would if we add it to .gitignore.

**Comment by mpkorstanje** [comment]
The entire thing is worth reading. But the phases specifically are:

https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#setting-up-your-project-to-use-the-build-lifecycle

Looks like you have the right one.

**Comment by aurelien-reeves** [comment]
The PR #17 should improve the management of the java ciDict.json. Thanks a lot for your help @mpkorstanje 

Now, we have to find a way for the ruby implementation
