### ISSUE TITLE
Clean up junk

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/create-meta#6]
Remove:

* [x] `.rsync`
* [x] `Makefile`
* [x] `default.mk`
* [x] `**/ciDict.json`

Add:

* [x] `RELEASING.md`
* [x] `CONTRIBUTING.md` 
  * [x] Move the readme's `## Adding support for new CI servers` paragraph here
  * [x] Remove paragraph about `rsync_files`
  * [x] Update instructions about how to run tests
* [x] `ARCHITECTURE.md`
  * [x] Move the readme's `## CI definitions` paragraph here.

**Comment by aurelien-reeves** [comment]
Will do that quickly
Thanks for the todo list actually!

**Comment by aurelien-reeves** [comment]
Did some clean-up here: #11

**Comment by aurelien-reeves** [comment]
Done the release process: #12
